# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение объявлений
GET {{baseUrl}}/adv/
Content-Type: application/json

###

# создание объявления
POST {{baseUrl}}/adv/
Content-Type: application/json
Authorization: Token bc2ead6de1fc15d63237ac214558c36da4e17995

{
  "title": "Шкаф IKEA",
  "description": "Срочно"
}

###

# удаление объявления тем же пользователем
DELETE {{baseUrl}}/adv/2/
Authorization: Token bc2ead6de1fc15d63237ac214558c36da4e17995

###

# удаление объявления другим пользователем
DELETE {{baseUrl}}/adv/2/
Authorization: Token 976cef1f0150e5c933e9cc2ac3ca8c87dd9c168e


###

# попытка поменять объявление
PATCH {{baseUrl}}/adv/4/
Content-Type: application/json
Authorization: Token bc2ead6de1fc15d63237ac214558c36da4e17995

{
  "status": "CLOSED"
}

###

# фильтрация по создателю
GET {{baseUrl}}/adv/?creator=2
Content-Type: application/json

###

# фильтрация по дате
GET {{baseUrl}}/adv/?created_at_before=2020-10-01
Content-Type: application/json
